// ========================================
// Veer Teja Electronics — Product Data
// Images: User-provided via iili.io CDN
// ========================================

export const CATEGORIES = [
  { id: '1', name: 'MCB & DB', nameEn: 'MCB & Board', slug: 'mcb-db', icon: '⚡', imageUrl: 'https://iili.io/C9eDwiP.jpg' },
  { id: '2', name: 'स्विच & सॉकेट', nameEn: 'Switch & Socket', slug: 'switch-socket', icon: '🔌', imageUrl: 'https://iili.io/C9ebdq7.jpg' },
  { id: '3', name: 'पंखा', nameEn: 'Fan', slug: 'fan', icon: '🌀', imageUrl: 'https://iili.io/C9k99yu.jpg' },
  { id: '4', name: 'कूलर', nameEn: 'Cooler', slug: 'cooler', icon: '❄️', imageUrl: 'https://iili.io/C9em2Qp.jpg' },
  { id: '5', name: 'वायर & केबल', nameEn: 'Wire & Cable', slug: 'wiring-cable', icon: '🔧', imageUrl: 'https://iili.io/C9eyT1S.jpg' },
  { id: '6', name: 'पानी की टंकी / कैन', nameEn: 'Water Tank & Can', slug: 'water-can', icon: '💧', imageUrl: 'https://iili.io/C9eym37.jpg' },
  { id: '7', name: 'मोटर & पम्प', nameEn: 'Motors & Pumps', slug: 'motor-pump', icon: '⚙️', imageUrl: 'https://iili.io/C9epAOJ.jpg' },
  { id: '8', name: 'LED लाइट', nameEn: 'LED Lights', slug: 'led-light', icon: '💡', imageUrl: 'https://iili.io/C9epMRs.jpg' },
];

export const SERVICES = [
  { id: '1', name: 'Cooler Repair', nameHi: 'कूलर मरम्मत', slug: 'cooler-repair', price: 299, duration: 'Same Day', icon: '❄️', description: 'Professional air cooler repair & service. All brands covered.', descriptionHi: 'प्रोफेशनल एयर कूलर मरम्मत और सर्विस। सभी ब्रांड।', isFeatured: true, imageUrl: 'https://iili.io/C9em2Qp.jpg' },
  { id: '2', name: 'Fan Repair', nameHi: 'पंखा मरम्मत', slug: 'fan-repair', price: 199, duration: 'Same Day', icon: '🌀', description: 'Ceiling, table & exhaust fan repair. Same day service.', descriptionHi: 'सीलिंग, टेबल और एग्जॉस्ट पंखा मरम्मत। उसी दिन सेवा।', isFeatured: true, imageUrl: 'https://iili.io/C9emKGI.jpg' },
  { id: '3', name: 'Refrigerator Repair', nameHi: 'फ्रिज मरम्मत', slug: 'fridge-repair', price: 399, duration: '1-2 Days', icon: '🧊', description: 'All brands refrigerator repair. Gas refilling & compressor.', descriptionHi: 'सभी ब्रांड फ्रिज मरम्मत। गैस रिफिलिंग और कम्प्रेसर।', isFeatured: true, imageUrl: 'https://iili.io/C9emB3X.jpg' },
  { id: '4', name: 'Washing Machine Repair', nameHi: 'वाशिंग मशीन मरम्मत', slug: 'washing-machine-repair', price: 499, duration: '1-2 Days', icon: '🧺', description: 'Front load & top load washing machine repair.', descriptionHi: 'फ्रंट लोड और टॉप लोड वाशिंग मशीन मरम्मत।', isFeatured: true, imageUrl: 'https://iili.io/C9emCan.jpg' },
  { id: '5', name: 'Inverter Service', nameHi: 'इन्वेर्टर सर्विस', slug: 'inverter-service', price: 349, duration: 'Same Day', icon: '🔋', description: 'Inverter repair & battery service. All brands.', descriptionHi: 'इन्वेर्टर मरम्मत और बैटरी सर्विस। सभी ब्रांड।', isFeatured: true, imageUrl: 'https://iili.io/C9epqoQ.jpg' },
  { id: '6', name: 'LED TV Repair', nameHi: 'LED टीवी मरम्मत', slug: 'led-tv-repair', price: 599, duration: '2-3 Days', icon: '📺', description: 'LED & Smart TV repair. Panel & board replacement.', descriptionHi: 'LED और स्मार्ट टीवी मरम्मत। पैनल और बोर्ड रिप्लेसमेंट।', imageUrl: 'https://iili.io/C9k9Ca1.jpg' },
  { id: '7', name: 'Motor Winding', nameHi: 'मोटर वाइंडिंग', slug: 'motor-winding', price: 799, duration: '2-3 Days', icon: '⚙️', description: 'Electric motor winding & rewinding. All sizes.', descriptionHi: 'इलेक्ट्रिक मोटर वाइंडिंग और रिवाइंडिंग। सभी साइज।', imageUrl: 'https://iili.io/C9kJdqQ.jpg' },
  { id: '8', name: 'Water Pump Repair', nameHi: 'पानी पम्प मरम्मत', slug: 'water-pump-repair', price: 449, duration: 'Same Day', icon: '🚰', description: 'Submersible & surface pump repair. All brands.', descriptionHi: 'सबमर्सिबल और सरफेस पम्प मरम्मत। सभी ब्रांड।', imageUrl: 'https://iili.io/C9kJHLx.jpg' },
  { id: '9', name: 'Wiring & Fitting', nameHi: 'वायरिंग और फिटिंग', slug: 'wiring-fitting', price: 699, duration: 'Same Day', icon: '🔌', description: 'Complete home & shop electrical wiring.', descriptionHi: 'घर और दुकान की पूरी इलेक्ट्रिकल वायरिंग।', imageUrl: 'https://iili.io/C9k9f6B.jpg' },
  { id: '10', name: 'MCB & Panel Work', nameHi: 'MCB & पैनल काम', slug: 'mcb-panel-work', price: 599, duration: 'Same Day', icon: '⚡', description: 'MCB fitting, DB panel work & safety upgrades.', descriptionHi: 'MCB फिटिंग, DB पैनल काम और सुरक्षा अपग्रेड।', imageUrl: 'https://iili.io/C9eDe0F.jpg' },
  { id: '11', name: 'Geyser Repair', nameHi: 'गीजर मरम्मत', slug: 'geyser-repair', price: 399, duration: 'Same Day', icon: '🚿', description: 'Water heater & geyser repair. Element & thermostat.', descriptionHi: 'वाटर हीटर और गीजर मरम्मत। एलिमेंट और थर्मोस्टेट।', imageUrl: 'https://iili.io/C9emoyG.jpg' },
  { id: '12', name: 'Mixer/Grinder Repair', nameHi: 'मिक्सर/चक्की मरम्मत', slug: 'mixer-repair', price: 249, duration: 'Same Day', icon: '🌀', description: 'Mixer, grinder & chakki motor repair.', descriptionHi: 'मिक्सर, ग्राइंडर और चक्की मोटर मरम्मत।', imageUrl: 'https://iili.io/C9emzuf.jpg' },
];

export const PRODUCTS = [
  {
    id: '1',
    name: '',
    nameHi: '',
    slug: 'product-1',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White plastic electrical junction box with multiple outlets']
  },
  {
    id: '2',
    name: '',
    nameHi: '',
    slug: 'product-2',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Combined box with MCB, socket, and switch']
  },
  {
    id: '3',
    name: '',
    nameHi: '',
    slug: 'product-3',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Snipper Gold 32A Miniature Circuit Breaker']
  },
  {
    id: '4',
    name: '',
    nameHi: '',
    slug: 'product-4',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Snipper Gold Classy Bed Switch for bedside lamps']
  },
  {
    id: '5',
    name: '',
    nameHi: '',
    slug: 'product-5',
    price: 2,
    mrp: 2,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['Two-pin electrical plug for Indian sockets']
  },
  {
    id: '6',
    name: '',
    nameHi: '',
    slug: 'product-6',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White plastic box for mounting electrical switches']
  },
  {
    id: '7',
    name: '',
    nameHi: '',
    slug: 'product-7',
    price: 2,
    mrp: 2,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['Variety of colored two-pin electrical plugs']
  },
  {
    id: '8',
    name: '',
    nameHi: '',
    slug: 'product-8',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Assortment of switches, sockets, and modular plates']
  },
  {
    id: '9',
    name: '',
    nameHi: '',
    slug: 'product-9',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['Electrical power outlet with screw terminals']
  },
  {
    id: '10',
    name: '',
    nameHi: '',
    slug: 'product-10',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹400',
    images: ['Snipper Gold DP Isolator C40 and C63']
  },
  {
    id: '11',
    name: '',
    nameHi: '',
    slug: 'product-11',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White bulb holder with red interior']
  },
  {
    id: '12',
    name: '',
    nameHi: '',
    slug: 'product-12',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['Collection of different types of bulb holders']
  },
  {
    id: '13',
    name: '',
    nameHi: '',
    slug: 'product-13',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Modular electrical switches and accessories']
  },
  {
    id: '14',
    name: '',
    nameHi: '',
    slug: 'product-14',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Universal travel adapter']
  },
  {
    id: '15',
    name: '',
    nameHi: '',
    slug: 'product-15',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['Electrical switch and socket combination']
  },
  {
    id: '16',
    name: '',
    nameHi: '',
    slug: 'product-16',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Modular electrical sockets']
  },
  {
    id: '17',
    name: '',
    nameHi: '',
    slug: 'product-17',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White pendant switch for electrical applications']
  },
  {
    id: '18',
    name: '',
    nameHi: '',
    slug: 'product-18',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹40',
    images: ['White bulb holder for ceiling or wall mount']
  },
  {
    id: '19',
    name: '',
    nameHi: '',
    slug: 'product-19',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White angle bulb holder with colored interior']
  },
  {
    id: '20',
    name: '',
    nameHi: '',
    slug: 'product-20',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['6amp combined box with switch and socket']
  },
  {
    id: '21',
    name: '',
    nameHi: '',
    slug: 'product-21',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White bulb holder for ceiling or wall mounting']
  },
  {
    id: '22',
    name: '',
    nameHi: '',
    slug: 'product-22',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['White plastic switch box for electrical fittings']
  },
  {
    id: '23',
    name: '',
    nameHi: '',
    slug: 'product-23',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['White switch board with switches and sockets']
  },
  {
    id: '24',
    name: '',
    nameHi: '',
    slug: 'product-24',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹60',
    images: ['Square white bulb holder for electrical connections']
  },
  {
    id: '25',
    name: '',
    nameHi: '',
    slug: 'product-25',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹500',
    images: ['White modular switchboard with multiple sockets and switches']
  },
  {
    id: '26',
    name: '',
    nameHi: '',
    slug: 'product-26',
    price: 3,
    mrp: 3,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White 3-pin plug for electrical appliances']
  },
  {
    id: '27',
    name: '',
    nameHi: '',
    slug: 'product-27',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White multi-plug adapter with multiple sockets']
  },
  {
    id: '28',
    name: '',
    nameHi: '',
    slug: 'product-28',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White Snipper Gold electrical socket with ISI mark']
  },
  {
    id: '29',
    name: '',
    nameHi: '',
    slug: 'product-29',
    price: 3,
    mrp: 3,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White 3-pin plug for Indian electrical outlets']
  },
  {
    id: '30',
    name: '',
    nameHi: '',
    slug: 'product-30',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White bulb holder with red interior']
  },
  {
    id: '31',
    name: '',
    nameHi: '',
    slug: 'product-31',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['Assortment of white electrical switches and socket']
  },
  {
    id: '32',
    name: '',
    nameHi: '',
    slug: 'product-32',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Back view of electrical switches and socket']
  },
  {
    id: '33',
    name: '',
    nameHi: '',
    slug: 'product-33',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['Two 16A switches and a universal socket']
  },
  {
    id: '34',
    name: '',
    nameHi: '',
    slug: 'product-34',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹300',
    images: ['Single switch and a 3-pin socket']
  },
  {
    id: '35',
    name: '',
    nameHi: '',
    slug: 'product-35',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['Universal socket and two switches']
  },
  {
    id: '36',
    name: '',
    nameHi: '',
    slug: 'product-36',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹300',
    images: ['Doorbell and a socket']
  },
  {
    id: '37',
    name: '',
    nameHi: '',
    slug: 'product-37',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['32A, 240V AC, 50Hz, C-32, Snapper Gold']
  },
  {
    id: '38',
    name: '',
    nameHi: '',
    slug: 'product-38',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White electrical switch with silver accent']
  },
  {
    id: '39',
    name: '',
    nameHi: '',
    slug: 'product-39',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Two white switches on a single plate']
  },
  {
    id: '40',
    name: '',
    nameHi: '',
    slug: 'product-40',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Coaxial socket and power socket on plate']
  },
  {
    id: '41',
    name: '',
    nameHi: '',
    slug: 'product-41',
    price: 2,
    mrp: 2,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['Blue 2-pin plug for Indian electrical outlets']
  },
  {
    id: '42',
    name: '',
    nameHi: '',
    slug: 'product-42',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['White multi-socket box with switches']
  },
  {
    id: '43',
    name: '',
    nameHi: '',
    slug: 'product-43',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹120',
    images: ['White fan speed regulator with 0-4 settings']
  },
  {
    id: '44',
    name: '',
    nameHi: '',
    slug: 'product-44',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White circular fan canopy for ceiling fans']
  },
  {
    id: '45',
    name: '',
    nameHi: '',
    slug: 'product-45',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White plastic switchboard box with two slots.']
  },
  {
    id: '46',
    name: '',
    nameHi: '',
    slug: 'product-46',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹40',
    images: ['White 16 Ampere electrical switch.']
  },
  {
    id: '47',
    name: '',
    nameHi: '',
    slug: 'product-47',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['Snipper Gold multi-pin electrical plug adapter.']
  },
  {
    id: '48',
    name: '',
    nameHi: '',
    slug: 'product-48',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹60',
    images: ['Heavy duty indicator with red light.']
  },
  {
    id: '49',
    name: '',
    nameHi: '',
    slug: 'product-49',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White plastic electrical switch plate with multiple slots']
  },
  {
    id: '50',
    name: '',
    nameHi: '',
    slug: 'product-50',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White plastic electrical junction box with mounting posts']
  },
  {
    id: '51',
    name: '',
    nameHi: '',
    slug: 'product-51',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White plastic electrical conduit box']
  },
  {
    id: '52',
    name: '',
    nameHi: '',
    slug: 'product-52',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White plastic electrical gang box, single and double']
  },
  {
    id: '53',
    name: '',
    nameHi: '',
    slug: 'product-53',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White modular switch with three switches']
  },
  {
    id: '54',
    name: '',
    nameHi: '',
    slug: 'product-54',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['Various white electrical switch and socket boards']
  },
  {
    id: '55',
    name: '',
    nameHi: '',
    slug: 'product-55',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹100',
    images: ['Brown wooden switch plate with silver frame']
  },
  {
    id: '56',
    name: '',
    nameHi: '',
    slug: 'product-56',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White plastic modular switch boxes of various sizes']
  },
  {
    id: '57',
    name: '',
    nameHi: '',
    slug: 'product-57',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical switch for controlling power flow']
  },
  {
    id: '58',
    name: '',
    nameHi: '',
    slug: 'product-58',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical socket with multiple plug options']
  },
  {
    id: '59',
    name: '',
    nameHi: '',
    slug: 'product-59',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Device to hold and connect a lamp']
  },
  {
    id: '60',
    name: '',
    nameHi: '',
    slug: 'product-60',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Connector to connect electrical devices to power']
  },
  {
    id: '61',
    name: '',
    nameHi: '',
    slug: 'product-61',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['White electrical switch for home wiring']
  },
  {
    id: '62',
    name: '',
    nameHi: '',
    slug: 'product-62',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Snipper Gold 6A 240V AC 3 Pin Top']
  },
  {
    id: '63',
    name: '',
    nameHi: '',
    slug: 'product-63',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White 3 pin plug for electrical appliances']
  },
  {
    id: '64',
    name: '',
    nameHi: '',
    slug: 'product-64',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Snipper Gold 2m Bell push with indicator']
  },
  {
    id: '65',
    name: '',
    nameHi: '',
    slug: 'product-65',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Combined box with MCB for electrical connections']
  },
  {
    id: '66',
    name: '',
    nameHi: '',
    slug: 'product-66',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White electrical socket and switch combination']
  },
  {
    id: '67',
    name: '',
    nameHi: '',
    slug: 'product-67',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['32A DP electrical switch for power control']
  },
  {
    id: '68',
    name: '',
    nameHi: '',
    slug: 'product-68',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White electrical switch boxes for housing switches']
  },
  {
    id: '69',
    name: '',
    nameHi: '',
    slug: 'product-69',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical transformer for voltage conversion']
  },
  {
    id: '70',
    name: '',
    nameHi: '',
    slug: 'product-70',
    price: 2,
    mrp: 2,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['Two-pin electrical plug for appliances']
  },
  {
    id: '71',
    name: '',
    nameHi: '',
    slug: 'product-71',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['Ceiling mounted bulb holder']
  },
  {
    id: '72',
    name: '',
    nameHi: '',
    slug: 'product-72',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['Electrical socket with on/off switch']
  },
  {
    id: '73',
    name: '',
    nameHi: '',
    slug: 'product-73',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['6A, 240V AC Polycarbonate 3 Pin Top']
  },
  {
    id: '74',
    name: '',
    nameHi: '',
    slug: 'product-74',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['Heavy Duty 32AMP-250V Snipper Gold Switch']
  },
  {
    id: '75',
    name: '',
    nameHi: '',
    slug: 'product-75',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['White Light Switch']
  },
  {
    id: '76',
    name: '',
    nameHi: '',
    slug: 'product-76',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹40',
    images: ['White Ceiling Rose']
  },
  {
    id: '77',
    name: '',
    nameHi: '',
    slug: 'product-77',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['Electrical outlet for modular switchboard']
  },
  {
    id: '78',
    name: '',
    nameHi: '',
    slug: 'product-78',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['Snipper Gold modular switchboard with three switches']
  },
  {
    id: '79',
    name: '',
    nameHi: '',
    slug: 'product-79',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['Black bulb holder with brass contact']
  },
  {
    id: '80',
    name: '',
    nameHi: '',
    slug: 'product-80',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['White modular switch for electrical circuits']
  },
  {
    id: '81',
    name: '',
    nameHi: '',
    slug: 'product-81',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White 5 pin socket with attached switch']
  },
  {
    id: '82',
    name: '',
    nameHi: '',
    slug: 'product-82',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹120',
    images: ['White 5 pin electrical socket']
  },
  {
    id: '83',
    name: '',
    nameHi: '',
    slug: 'product-83',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['White bulb holder with red interior']
  },
  {
    id: '84',
    name: '',
    nameHi: '',
    slug: 'product-84',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹100',
    images: ['White electrical switch 25A and 40A D.P.']
  },
  {
    id: '85',
    name: '',
    nameHi: '',
    slug: 'product-85',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Classy bed switch with quality assurance']
  },
  {
    id: '86',
    name: '',
    nameHi: '',
    slug: 'product-86',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Fan speed controller with multiple settings']
  },
  {
    id: '87',
    name: '',
    nameHi: '',
    slug: 'product-87',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['25A motor starter with on/off switch']
  },
  {
    id: '88',
    name: '',
    nameHi: '',
    slug: 'product-88',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White plastic electrical switch box']
  },
  {
    id: '89',
    name: '',
    nameHi: '',
    slug: 'product-89',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['White modular switch for electrical installations']
  },
  {
    id: '90',
    name: '',
    nameHi: '',
    slug: 'product-90',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['Various types of electrical plugs and sockets']
  },
  {
    id: '91',
    name: '',
    nameHi: '',
    slug: 'product-91',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White 18 module electrical switch plate']
  },
  {
    id: '92',
    name: '',
    nameHi: '',
    slug: 'product-92',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White modular gang box for electrical switches']
  },
  {
    id: '93',
    name: '',
    nameHi: '',
    slug: 'product-93',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50-₹500',
    images: ['Various electrical switches and sockets for home use']
  },
  {
    id: '94',
    name: '',
    nameHi: '',
    slug: 'product-94',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Industrial air cooler with digital display']
  },
  {
    id: '95',
    name: '',
    nameHi: '',
    slug: 'product-95',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Stainless steel industrial air cooler']
  },
  {
    id: '96',
    name: '',
    nameHi: '',
    slug: 'product-96',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Industrial air cooler on a stainless steel table']
  },
  {
    id: '97',
    name: '',
    nameHi: '',
    slug: 'product-97',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Stainless steel air cooler for industrial use']
  },
  {
    id: '98',
    name: '',
    nameHi: '',
    slug: 'product-98',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['150W LED flood light with IP66 rating']
  },
  {
    id: '99',
    name: '',
    nameHi: '',
    slug: 'product-99',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['90 Litres capacity air cooler with honey pad']
  },
  {
    id: '100',
    name: '',
    nameHi: '',
    slug: 'product-100',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['90 Litres capacity air cooler with grass pad']
  },
  {
    id: '101',
    name: '',
    nameHi: '',
    slug: 'product-101',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['90 Litres, 1 1/4 Cop. Baring Motor, 17 CRC Blade']
  },
  {
    id: '102',
    name: '',
    nameHi: '',
    slug: 'product-102',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['90 Litres, 1/4 Cop. Baring Motor, 18" Climatizer Blade']
  },
  {
    id: '103',
    name: '',
    nameHi: '',
    slug: 'product-103',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['80 Litres, 1/4 Cop. Baring Motor, 18" Climatizer Blade']
  },
  {
    id: '104',
    name: '',
    nameHi: '',
    slug: 'product-104',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['90 Litres, 1/10 Alu. Baring Motor, 15" CRC Blade']
  },
  {
    id: '105',
    name: '',
    nameHi: '',
    slug: 'product-105',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['100 Litres Capacity, Honeypad, 15" CRC Blade']
  },
  {
    id: '106',
    name: '',
    nameHi: '',
    slug: 'product-106',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['150 Litres Capacity, Honeypad, 20" Climatizer Blade']
  },
  {
    id: '107',
    name: '',
    nameHi: '',
    slug: 'product-107',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['70 Litres Capacity, 15" CRC Blade, 18 Watt Pump']
  },
  {
    id: '108',
    name: '',
    nameHi: '',
    slug: 'product-108',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['50 Litres Capacity, Honeypad, Swing, Blower, 12 Watt Pump']
  },
  {
    id: '109',
    name: '',
    nameHi: '',
    slug: 'product-109',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['90 Litres Capacity, Honeypad, 1/10 Aluminum Motor']
  },
  {
    id: '110',
    name: '',
    nameHi: '',
    slug: 'product-110',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['20 Litres Capacity, Honeypad, Blower, Swing']
  },
  {
    id: '111',
    name: '',
    nameHi: '',
    slug: 'product-111',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['90 Litres Capacity, 1 1/2 Cop. Baring Motor']
  },
  {
    id: '112',
    name: '',
    nameHi: '',
    slug: 'product-112',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['90 Litres Capacity, 1 1/2 Cop. Baring Motor']
  },
  {
    id: '113',
    name: '',
    nameHi: '',
    slug: 'product-113',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['60 Litres Capacity, 2 Season Motor Guarantee']
  },
  {
    id: '114',
    name: '',
    nameHi: '',
    slug: 'product-114',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['60 Litres Capacity, 2 Season Motor Guarantee']
  },
  {
    id: '115',
    name: '',
    nameHi: '',
    slug: 'product-115',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Multiple colors available, wrapped in plastic']
  },
  {
    id: '116',
    name: '',
    nameHi: '',
    slug: 'product-116',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Blue color, wrapped in plastic']
  },
  {
    id: '117',
    name: '',
    nameHi: '',
    slug: 'product-117',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹6000',
    images: ['White Hind Air Cooler with wheels']
  },
  {
    id: '118',
    name: '',
    nameHi: '',
    slug: 'product-118',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹6500',
    images: ['Blue Hind Air Cooler with wheels']
  },
  {
    id: '119',
    name: '',
    nameHi: '',
    slug: 'product-119',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹6200',
    images: ['White Hind Air Cooler packed']
  },
  {
    id: '120',
    name: '',
    nameHi: '',
    slug: 'product-120',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹6300',
    images: ['Beige Hind Air Cooler packed']
  },
  {
    id: '121',
    name: '',
    nameHi: '',
    slug: 'product-121',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹7,000',
    images: ['White air cooler with black fan grill']
  },
  {
    id: '122',
    name: '',
    nameHi: '',
    slug: 'product-122',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹6,500',
    images: ['Blue air cooler with white fan blades']
  },
  {
    id: '123',
    name: '',
    nameHi: '',
    slug: 'product-123',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹7,000',
    images: ['Beige air cooler with black fan blades']
  },
  {
    id: '124',
    name: '',
    nameHi: '',
    slug: 'product-124',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹7,000',
    images: ['White air cooler with red accents']
  },
  {
    id: '125',
    name: '',
    nameHi: '',
    slug: 'product-125',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White air cooler with wheels']
  },
  {
    id: '126',
    name: '',
    nameHi: '',
    slug: 'product-126',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White air cooler with cooling pads']
  },
  {
    id: '127',
    name: '',
    nameHi: '',
    slug: 'product-127',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White air cooler with honeycomb cooling pads']
  },
  {
    id: '128',
    name: '',
    nameHi: '',
    slug: 'product-128',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White air cooler with honeycomb cooling pads']
  },
  {
    id: '129',
    name: '',
    nameHi: '',
    slug: 'product-129',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['2.5 Sq.mm, 3 Cables, 90m Length']
  },
  {
    id: '130',
    name: '',
    nameHi: '',
    slug: 'product-130',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Flame Retardant (FR) PVC Insulated Industrial Cables']
  },
  {
    id: '131',
    name: '',
    nameHi: '',
    slug: 'product-131',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['1.0 Sq.mm']
  },
  {
    id: '132',
    name: '',
    nameHi: '',
    slug: 'product-132',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['FR-PVC with 105°C base insulation']
  },
  {
    id: '133',
    name: '',
    nameHi: '',
    slug: 'product-133',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['1.0 sq. mm Genuine FR PVC Multi-Strand Cables']
  },
  {
    id: '134',
    name: '',
    nameHi: '',
    slug: 'product-134',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['2.5 sq mm Insulated Industrial Cables']
  },
  {
    id: '135',
    name: '',
    nameHi: '',
    slug: 'product-135',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Securexza PVC Insulated Copper Conductor']
  },
  {
    id: '136',
    name: '',
    nameHi: '',
    slug: 'product-136',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Cables that don\\'t catch fire']
  },
  {
    id: '137',
    name: '',
    nameHi: '',
    slug: 'product-137',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical wire for household and industrial use']
  },
  {
    id: '138',
    name: '',
    nameHi: '',
    slug: 'product-138',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Flame retardant electrical wire for safety']
  },
  {
    id: '139',
    name: '',
    nameHi: '',
    slug: 'product-139',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['High-quality electrical wire for various applications']
  },
  {
    id: '140',
    name: '',
    nameHi: '',
    slug: 'product-140',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['PVC insulated industrial cable with flame retardant properties']
  },
  {
    id: '141',
    name: '',
    nameHi: '',
    slug: 'product-141',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['PVC insulated industrial cables by Panasonic']
  },
  {
    id: '142',
    name: '',
    nameHi: '',
    slug: 'product-142',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹2115.00',
    images: ['Eco safe wires, 3 layered, 90m length']
  },
  {
    id: '143',
    name: '',
    nameHi: '',
    slug: 'product-143',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['PVC insulated industrial cables by Panasonic']
  },
  {
    id: '144',
    name: '',
    nameHi: '',
    slug: 'product-144',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['PVC insulated industrial cables by Polycab']
  },
  {
    id: '145',
    name: '',
    nameHi: '',
    slug: 'product-145',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Polycab Optima wire of different sizes']
  },
  {
    id: '146',
    name: '',
    nameHi: '',
    slug: 'product-146',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Finolex FR PVC insulated industrial cables']
  },
  {
    id: '147',
    name: '',
    nameHi: '',
    slug: 'product-147',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Greatwhite FR-PVC insulated industrial cable']
  },
  {
    id: '148',
    name: '',
    nameHi: '',
    slug: 'product-148',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['RR Kabel wire of different sizes']
  },
  {
    id: '149',
    name: '',
    nameHi: '',
    slug: 'product-149',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical wire for home and industrial use']
  },
  {
    id: '150',
    name: '',
    nameHi: '',
    slug: 'product-150',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical fitting for ceiling light connection']
  },
  {
    id: '151',
    name: '',
    nameHi: '',
    slug: 'product-151',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical fitting for holding light bulbs']
  },
  {
    id: '152',
    name: '',
    nameHi: '',
    slug: 'product-152',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Election card, Aadhar card, PAN card']
  },
  {
    id: '153',
    name: '',
    nameHi: '',
    slug: 'product-153',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['Alkaline water purifier with hot water and copper']
  },
  {
    id: '154',
    name: '',
    nameHi: '',
    slug: 'product-154',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['BLDC Technology, 5 Star Rated, Made in India']
  },
  {
    id: '155',
    name: '',
    nameHi: '',
    slug: 'product-155',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['BLDC Technology, 5 Star Rated, Made in India']
  },
  {
    id: '156',
    name: '',
    nameHi: '',
    slug: 'product-156',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['White ceiling fan, 3 years warranty, Made in India']
  },
  {
    id: '157',
    name: '',
    nameHi: '',
    slug: 'product-157',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹2500',
    images: ['Jaguar Luker ceiling fan with 2 year warranty']
  },
  {
    id: '158',
    name: '',
    nameHi: '',
    slug: 'product-158',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹15000',
    images: ['Daewoo Kyong Alkaline Water Purifier with Copper']
  },
  {
    id: '159',
    name: '',
    nameHi: '',
    slug: 'product-159',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹3000',
    images: ['Black ceiling fan with decorative ceiling design']
  },
  {
    id: '160',
    name: '',
    nameHi: '',
    slug: 'product-160',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹3500',
    images: ['Luker Crown BLDC ceiling fan with 3 year warranty']
  },
  {
    id: '161',
    name: '',
    nameHi: '',
    slug: 'product-161',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1200',
    images: ['12 inch table fan for shop, showroom, kitchen']
  },
  {
    id: '162',
    name: '',
    nameHi: '',
    slug: 'product-162',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1100',
    images: ['12 inch table fan with superior grade electric steel']
  },
  {
    id: '163',
    name: '',
    nameHi: '',
    slug: 'product-163',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1000',
    images: ['Table fan with plastic cover']
  },
  {
    id: '164',
    name: '',
    nameHi: '',
    slug: 'product-164',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Black plastic fan blades']
  },
  {
    id: '165',
    name: '',
    nameHi: '',
    slug: 'product-165',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹800',
    images: ['Grey cooler motor with wires']
  },
  {
    id: '166',
    name: '',
    nameHi: '',
    slug: 'product-166',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['Stack of white plastic fan blades']
  },
  {
    id: '167',
    name: '',
    nameHi: '',
    slug: 'product-167',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['Grey plastic fan blades']
  },
  {
    id: '168',
    name: '',
    nameHi: '',
    slug: 'product-168',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1500',
    images: ['Major Power High Speed Ceiling Fan']
  },
  {
    id: '169',
    name: '',
    nameHi: '',
    slug: 'product-169',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1500',
    images: ['White and maroon Casta brand standing fan']
  },
  {
    id: '170',
    name: '',
    nameHi: '',
    slug: 'product-170',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1500',
    images: ['White and maroon Casta brand standing fan']
  },
  {
    id: '171',
    name: '',
    nameHi: '',
    slug: 'product-171',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['Coil of pink Winner brand PVC pipe']
  },
  {
    id: '172',
    name: '',
    nameHi: '',
    slug: 'product-172',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['Box of Khaitan premium wires and cables']
  },
  {
    id: '173',
    name: '',
    nameHi: '',
    slug: 'product-173',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['Energy efficient, high quality wires and cables']
  },
  {
    id: '174',
    name: '',
    nameHi: '',
    slug: 'product-174',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['Trust naam mein, perfect kaam mein, copper']
  },
  {
    id: '175',
    name: '',
    nameHi: '',
    slug: 'product-175',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['Smart choice begins here, 24x7 protection']
  },
  {
    id: '176',
    name: '',
    nameHi: '',
    slug: 'product-176',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹Unavailable',
    images: ['16A multi socket with 25A MCB combined switch']
  },
  {
    id: '177',
    name: '',
    nameHi: '',
    slug: 'product-177',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['6/16A, 240V A.C. ONLY, Quality Redefines']
  },
  {
    id: '179',
    name: '',
    nameHi: '',
    slug: 'product-179',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White plastic electrical switchboard surface box']
  },
  {
    id: '180',
    name: '',
    nameHi: '',
    slug: 'product-180',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White plastic electrical switchboard surface box']
  },
  {
    id: '181',
    name: '',
    nameHi: '',
    slug: 'product-181',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹5000',
    images: ['Blue air cooler on a cardboard box']
  },
  {
    id: '182',
    name: '',
    nameHi: '',
    slug: 'product-182',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹500',
    images: ['Motor for air cooler with Sparrow Capacitors box']
  },
  {
    id: '183',
    name: '',
    nameHi: '',
    slug: 'product-183',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹300',
    images: ['S.S. Combined with Box 6A 250 Volts ac.']
  },
  {
    id: '184',
    name: '',
    nameHi: '',
    slug: 'product-184',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White electrical socket with multiple holes']
  },
  {
    id: '185',
    name: '',
    nameHi: '',
    slug: 'product-185',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['6A, 250 Volts AC Double Combined']
  },
  {
    id: '186',
    name: '',
    nameHi: '',
    slug: 'product-186',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White modular plate with black inserts']
  },
  {
    id: '187',
    name: '',
    nameHi: '',
    slug: 'product-187',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White electrical box with brass inserts']
  },
  {
    id: '188',
    name: '',
    nameHi: '',
    slug: 'product-188',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White 6M modular plate']
  },
  {
    id: '189',
    name: '',
    nameHi: '',
    slug: 'product-189',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['Square shaped, orange and white plastic electrical box']
  },
  {
    id: '190',
    name: '',
    nameHi: '',
    slug: 'product-190',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['Various colors of electrical insulation tape in basket']
  },
  {
    id: '191',
    name: '',
    nameHi: '',
    slug: 'product-191',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1500',
    images: ['6.0 sq.mm, 220/440 V, Red color']
  },
  {
    id: '192',
    name: '',
    nameHi: '',
    slug: 'product-192',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹120',
    images: ['White Radion brand electrical sockets, different amp ratings']
  },
  {
    id: '192',
    name: '',
    nameHi: '',
    slug: 'product-192',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹120',
    images: ['White Radion brand electrical sockets, different amp ratings']
  },
  {
    id: '193',
    name: '',
    nameHi: '',
    slug: 'product-193',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Modular Accessories for electrical fittings']
  },
  {
    id: '194',
    name: '',
    nameHi: '',
    slug: 'product-194',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Pink water cooler for cold water storage']
  },
  {
    id: '195',
    name: '',
    nameHi: '',
    slug: 'product-195',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Blue water cooler with cool control system']
  },
  {
    id: '196',
    name: '',
    nameHi: '',
    slug: 'product-196',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Beige water cooler with cool control system']
  },
  {
    id: '197',
    name: '',
    nameHi: '',
    slug: 'product-197',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1200',
    images: ['Orange water cooler with ice cube design']
  },
  {
    id: '198',
    name: '',
    nameHi: '',
    slug: 'product-198',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1200',
    images: ['Green water cooler with ice cube design']
  },
  {
    id: '199',
    name: '',
    nameHi: '',
    slug: 'product-199',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Grey and black water cooler with tap']
  },
  {
    id: '200',
    name: '',
    nameHi: '',
    slug: 'product-200',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Orange and black water cooler with tap']
  },
  {
    id: '201',
    name: '',
    nameHi: '',
    slug: 'product-201',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Orange Panara water cooler for cold water storage']
  },
  {
    id: '202',
    name: '',
    nameHi: '',
    slug: 'product-202',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['8.5uF 440V capacitor for electrical appliances']
  },
  {
    id: '203',
    name: '',
    nameHi: '',
    slug: 'product-203',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹9999',
    images: ['300 DOM Bulb, MegaFon, Inverter, Cycle combo offer']
  },
  {
    id: '204',
    name: '',
    nameHi: '',
    slug: 'product-204',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹750',
    images: ['MZ M982 LED flashlight with orange case']
  },
  {
    id: '205',
    name: '',
    nameHi: '',
    slug: 'product-205',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['0.5W LED Plug & Play Night Lamp']
  },
  {
    id: '206',
    name: '',
    nameHi: '',
    slug: 'product-206',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['0.5W LED Plug & Play Night Lamp']
  },
  {
    id: '207',
    name: '',
    nameHi: '',
    slug: 'product-207',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹65',
    images: ['15W Crystal White 6500K 1500 LUMENS']
  },
  {
    id: '208',
    name: '',
    nameHi: '',
    slug: 'product-208',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹130',
    images: ['15/18W Inverter Bulb AC/DC Bulb']
  },
  {
    id: '209',
    name: '',
    nameHi: '',
    slug: 'product-209',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['9W LED bulb made in India']
  },
  {
    id: '210',
    name: '',
    nameHi: '',
    slug: 'product-210',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['0.5W LED bulb, plug and play']
  },
  {
    id: '211',
    name: '',
    nameHi: '',
    slug: 'product-211',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹200',
    images: ['Whole new generation of 3D lamp']
  },
  {
    id: '212',
    name: '',
    nameHi: '',
    slug: 'product-212',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White electrical switchboard with switches and sockets']
  },
  {
    id: '213',
    name: '',
    nameHi: '',
    slug: 'product-213',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹500',
    images: ['White modular switchboard with socket and switches']
  },
  {
    id: '214',
    name: '',
    nameHi: '',
    slug: 'product-214',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹650',
    images: ['Multi-functional electrical switchboard with sockets and switches']
  },
  {
    id: '215',
    name: '',
    nameHi: '',
    slug: 'product-215',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹300',
    images: ['White modular switchboard with socket and switches']
  },
  {
    id: '216',
    name: '',
    nameHi: '',
    slug: 'product-216',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White and blue bulb holder for lighting']
  },
  {
    id: '217',
    name: '',
    nameHi: '',
    slug: 'product-217',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['White switchboard with switches, sockets, and bulb holder']
  },
  {
    id: '218',
    name: '',
    nameHi: '',
    slug: 'product-218',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['White socket and switch combination on board']
  },
  {
    id: '219',
    name: '',
    nameHi: '',
    slug: 'product-219',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹600',
    images: ['Multiple switchboards with sockets and switches']
  },
  {
    id: '220',
    name: '',
    nameHi: '',
    slug: 'product-220',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹80',
    images: ['White bulb holder with wires attached']
  },
  {
    id: '221',
    name: '',
    nameHi: '',
    slug: 'product-221',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹500',
    images: ['Screwdrivers and wire stripper for electrical work']
  },
  {
    id: '222',
    name: '',
    nameHi: '',
    slug: 'product-222',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1500',
    images: ['6.0 SQ MM x 2 CORE TWIN 1100 U']
  },
  {
    id: '223',
    name: '',
    nameHi: '',
    slug: 'product-223',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹1200',
    images: ['Electrical wire for home and industrial use']
  },
  {
    id: '224',
    name: '',
    nameHi: '',
    slug: 'product-224',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹300',
    images: ['Alarm to prevent water tank overflow']
  },
  {
    id: '225',
    name: '',
    nameHi: '',
    slug: 'product-225',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹300',
    images: ['Black multi-socket extension cord with switch']
  },
  {
    id: '226',
    name: '',
    nameHi: '',
    slug: 'product-226',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹400',
    images: ['White round extension board with multiple sockets']
  },
  {
    id: '227',
    name: '',
    nameHi: '',
    slug: 'product-227',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['White switch board with two sockets and switches']
  },
  {
    id: '228',
    name: '',
    nameHi: '',
    slug: 'product-228',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['White switch board with multiple switches and socket']
  },
  {
    id: '229',
    name: '',
    nameHi: '',
    slug: 'product-229',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['Pink extension cord reel with multiple outlets']
  },
  {
    id: '230',
    name: '',
    nameHi: '',
    slug: 'product-230',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹400',
    images: ['White switch board with sockets and switches']
  },
  {
    id: '231',
    name: '',
    nameHi: '',
    slug: 'product-231',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹700',
    images: ['White switch board with multiple sockets and switches']
  },
  {
    id: '232',
    name: '',
    nameHi: '',
    slug: 'product-232',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹500',
    images: ['White switch board with sockets and switches']
  },
  {
    id: '233',
    name: '',
    nameHi: '',
    slug: 'product-233',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['White extension board with one socket and switch']
  },
  {
    id: '234',
    name: '',
    nameHi: '',
    slug: 'product-234',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['Extension board with two sockets and one switch']
  },
  {
    id: '235',
    name: '',
    nameHi: '',
    slug: 'product-235',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['White extension board with one socket and switch']
  },
  {
    id: '236',
    name: '',
    nameHi: '',
    slug: 'product-236',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹400',
    images: ['Extension board with socket, switches, bulb holder']
  },
  {
    id: '237',
    name: '',
    nameHi: '',
    slug: 'product-237',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White switch board with socket and switches']
  },
  {
    id: '238',
    name: '',
    nameHi: '',
    slug: 'product-238',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Backside of a white switch board']
  },
  {
    id: '239',
    name: '',
    nameHi: '',
    slug: 'product-239',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Double combined switch board in box']
  },
  {
    id: '240',
    name: '',
    nameHi: '',
    slug: 'product-240',
    price: 3,
    mrp: 3,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['White 3-pin electrical plug']
  },
  {
    id: '241',
    name: '',
    nameHi: '',
    slug: 'product-241',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹150',
    images: ['Multi-purpose electrical plug adapter for Indian sockets']
  },
  {
    id: '242',
    name: '',
    nameHi: '',
    slug: 'product-242',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['White socket with blue on/off switch']
  },
  {
    id: '243',
    name: '',
    nameHi: '',
    slug: 'product-243',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹200',
    images: ['White socket with white on/off switch']
  },
  {
    id: '244',
    name: '',
    nameHi: '',
    slug: 'product-244',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical shop with various products and staff']
  },
  {
    id: '245',
    name: '',
    nameHi: '',
    slug: 'product-245',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹50',
    images: ['Variety of colored electrical insulation tapes']
  },
  {
    id: '246',
    name: '',
    nameHi: '',
    slug: 'product-246',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹30',
    images: ['White indicator switch with red light']
  },
  {
    id: '247',
    name: '',
    nameHi: '',
    slug: 'product-247',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹250',
    images: ['White multi plug extension board with switch']
  },
  {
    id: '248',
    name: '',
    nameHi: '',
    slug: 'product-248',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹120',
    images: ['Low energy, high intensity LED spot light']
  },
  {
    id: '249',
    name: '',
    nameHi: '',
    slug: 'product-249',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['White extension board with two switches and sockets']
  },
  {
    id: '250',
    name: '',
    nameHi: '',
    slug: 'product-250',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['White extension board with two switches and sockets']
  },
  {
    id: '251',
    name: '',
    nameHi: '',
    slug: 'product-251',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Round LED panel light, 9W']
  },
  {
    id: '252',
    name: '',
    nameHi: '',
    slug: 'product-252',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: '₹350',
    images: ['White extension board with two switches and sockets']
  },
  {
    id: '253',
    name: '',
    nameHi: '',
    slug: 'product-253',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Electrical switchboard for mounting switches and sockets']
  },
  {
    id: '254',
    name: '',
    nameHi: '',
    slug: 'product-254',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Small 0.5W LED bulbs in various colors']
  },
  {
    id: '255',
    name: '',
    nameHi: '',
    slug: 'product-255',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Orange colored electrical extension cord with multiple outlets']
  },
  {
    id: '256',
    name: '',
    nameHi: '',
    slug: 'product-256',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Black and white immersion blender with box']
  },
  {
    id: '257',
    name: '',
    nameHi: '',
    slug: 'product-257',
    price: 999,
    mrp: 1198,
    discount: 20,
    brand: 'Generic',
    categoryId: '2',
    inStock: true,
    rating: 4.5,
    reviewCount: 10,
    description: 'Unavailable',
    images: ['Immersion blender with box']
  }
];

export const TESTIMONIALS = [
  { id: '1', name: 'रामचंद्र जी', location: 'जयसंगसर', review: 'Excellent service! My cooler was fixed within hours. Very professional team.', reviewHi: 'बहुत अच्छी सेवा! मेरा कूलर कुछ ही घंटों में ठीक हो गया। बहुत प्रोफेशनल टीम।', rating: 5, imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face' },
  { id: '2', name: 'सुनीता देवी', location: 'गोमटिया', review: 'Affordable prices and great quality work. My fan works like new now!', reviewHi: 'सस्ती कीमत और बढ़िया काम। मेरा पंखा अब नया जैसा काम करता है!', rating: 5, imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face' },
  { id: '3', name: 'मोहन लाल', location: 'सरदारशहर', review: 'Best inverter service in the area. Highly recommended!', reviewHi: 'इस इलाके में सबसे अच्छी इन्वेर्टर सेवा। जरूर सुझाऊंगा!', rating: 5, imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face' },
  { id: '4', name: 'पूजा शर्मा', location: 'राजस्थान', review: 'Quick turnaround for washing machine repair. Very satisfied with the service.', reviewHi: 'वाशिंग मशीन मरम्मत में जल्दी सेवा। सेवा से बहुत संतुष्ट।', rating: 4, imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face' },
  { id: '5', name: 'राजेश कुमार', location: 'जयपुर', review: 'Great deals on wholesale electronics. Best prices in town!', reviewHi: 'थोक इलेक्ट्रॉनिक्स में बढ़िया डील। शहर में सबसे अच्छी कीमतें!', rating: 5, imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face' },
];

export const BANNERS = [
  { id: '1', title: 'Repair Services', titleHi: 'मरम्मत सेवाएं', subtitle: 'कूलर • पंखा • फ्रिज • वाशिंग मशीन • इन्वेर्टर', imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1920&h=800&fit=crop', link: '/services', sortOrder: 1 },
  { id: '2', title: 'Inverter & Battery', titleHi: 'इन्वेर्टर और बैटरी', subtitle: 'बड़ी बचत • सभी ब्रांड • थोक दरें', imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492ac74e4?w=1920&h=800&fit=crop', link: '/products?category=inverter-battery', sortOrder: 2 },
  { id: '3', title: 'MCB & Electrical', titleHi: 'MCB & इलेक्ट्रिकल', subtitle: 'Switches • Sockets • Wiring • DB Panel', imageUrl: 'https://images.unsplash.com/photo-1558227691-41ea78a1f631?w=1920&h=800&fit=crop', link: '/products?category=mcb-db', sortOrder: 3 },
  { id: '4', title: 'Fans & Lights', titleHi: 'पंखे और लाइटें', subtitle: 'सभी ब्रांड • थोक दर • ISI मार्क्ड', imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1920&h=800&fit=crop', link: '/products?category=fan', sortOrder: 4 },
];

export const BRANDS = [
  { name: 'Havells', logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Havells_Logo.svg' },
  { name: 'Philips', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Philips_logo.svg' },
  { name: 'Polycab', logo: 'https://via.placeholder.com/120x45/1a237e/ffffff?text=Polycab' },
  { name: 'Anchor', logo: 'https://via.placeholder.com/120x45/e65100/ffffff?text=Anchor' },
  { name: 'Crompton', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Crompton_Greaves_logo.svg' },
  { name: 'Luminous', logo: 'https://via.placeholder.com/120x45/1a237e/ffffff?text=Luminous' },
  { name: 'Exide', logo: 'https://via.placeholder.com/120x45/e65100/ffffff?text=Exide' },
  { name: 'Syska', logo: 'https://via.placeholder.com/120x45/1a237e/ffffff?text=Syska' },
  { name: 'Legrand', logo: 'https://via.placeholder.com/120x45/e65100/ffffff?text=Legrand' },
  { name: 'Astral', logo: 'https://via.placeholder.com/120x45/1a237e/ffffff?text=Astral' },
  { name: 'Kirloskar', logo: 'https://via.placeholder.com/120x45/e65100/ffffff?text=Kirloskar' },
  { name: 'V-Guard', logo: 'https://via.placeholder.com/120x45/1a237e/ffffff?text=V-Guard' },
];

export const CONTACTS = {
  mesh: {
    name: 'मेश सारण',
    nameEn: 'Mesh Saran',
    role: 'Electrician',
    area: 'जयसंगसर वाले',
    phones: ['9928330252', '9929124331'],
    whatsapp: '919928330252',
  },
  pappuram: {
    name: 'पप्पूराम सारण',
    nameEn: 'Pappuram Saran',
    role: 'Shop Owner',
    area: 'गोमटिया वाले',
    phones: ['6350211515', '8955293732'],
    whatsapp: '916350211515',
  },
};

export const MARQUEE_MESSAGES = [
  '🔥 स्पेशल ऑफर: MCB & DB Panel पर 30% छूट',
  '💡 LED लाइट थोक में खरीदें — बड़ी बचत पाएं',
  '⚡ इन्वेर्टर बैटरी पर 15% ऑफ — Limited Time',
  '🛠️ घर पर सर्विस: Call करें 9928330252',
  '⭐ 20+ साल का भरोसा — हजारों संतुष्ट ग्राहक',
  '🌀 सभी ब्रांड के पंखे — थोक एवं खुदरा उपलब्ध',
];

export const STATS = {
  customers: 5000,
  years: 20,
  services: 12,
  brands: 100,
};

// Shop images (user provided)
export const REAL_IMAGES = {
  hero: [
    'https://iili.io/C9eDwiP.jpg',
    'https://iili.io/C9epHl9.jpg',
    'https://iili.io/C9em9yJ.jpg',
  ],
  repair: 'https://iili.io/C9emCan.jpg',
  shop: 'https://iili.io/C9k99yu.jpg',
  team: 'https://iili.io/C9kJ9Xj.jpg',
};